services:
  bot:
    image: sutaai/dockerized-red
    volumes:
      - data:/app
    environment:
      TOKEN: $REDBOT_TOKEN
      INSTANCE_NAME: bot
      STORAGE: json
      TRUST_HOSTS: github.com
    secrets:
      - ssh-key

volumes:
  data:

secrets:
  ssh-key:
    file: /home/sutaai/.ssh/id_ed25519
