services:
  bot:
    build:
      context: https://github.com/Sutaai/dockerized-red
      args:
        PYTHON_VERSION: "3.11"

    volumes:
      - data:/app
    environment:
      INSTANCE_NAME: bot
      STORAGE: json
    secrets:
      - ssh-key

volumes:
  data:
