services:
  bot:
    image: sutaai/dockerized-red
    volumes:
      - bot-data:/app
    environment:
      INSTANCE_NAME: bot
      STORAGE: postgres
      PSQL_HOST: db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  bot-data:
  db-data:
